apiVersion: v1
kind: Pod
metadata:
  name: nginx
  lables:
    environment: dev
    app: frontend
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
        name: http-web-svc