apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    com.project.author: Vishwa
    com.project.name: roboshop
spec:
  containers:
  - name: nginx-labels
    image: nginx
    ports:
    - containerPort: 80